### ISSUE TITLE
[BUG] Teams Meeting unable to add a room or ressource to a teams onlinemeeting

### ISSUE THREAD

**Issue by rainer-haeberle** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#104]
**HCL Product Version**
Which version of the Notes Client is in use.
11.0.1 Standard German with FP3 and the required Mailtemplate

**Describe the bug**

We are using DOMI Integration Feature on notes mail template v 11.0.3 FP3
In general we're able to schedule a teams online meeting using the features provided.

Unfortunately once we add a room or resource from resource reservation (template Version 11.0.1) we get an Pop-Up message with a blue dot containing a question mark followed by the text: "Please select a online meeting room for this meeting."
Only an [OK] button is available.

even if we click on this [OK] button we won't be able to send changed meeting details to other invited users.
The message box is shown again.

you even can't update the teams meeting or delete the existing and create a new one.

Others invited to this meeting cannot click on accept or decline as well without running into message.

please check to reproduce this behavior in your environment.

Again: using only "normal" attendees do not show this effect. 

Effect comes up only once you select or add a room or resource to a teams meeting.

**Error Message**
If an error message is displayed, include details here. Quickly identifying the code causing the error will help to more quickly resolve it.

Pop-Up message with a blue dot containing a question mark followed by the text: 
"Please select a online meeting room for this meeting."
Only an [OK] button is available.

**To Reproduce**
1. Go to 'Mail-Calender and create a new meeting '
2. Click on 'Add Teams Online Meeting'
3. Add Attendees and send invitation (including Teams meeting details)
4. Now reopen the meeting and add a room from resource reservation.
5. Click on send invitation 
6. Enjoy the show

**Expected behavior**
OK It tells me to create a new Online Meeting room.
I click on Update Teams Meeting, or delete Teamsmeeting and create a new One.
But this doesn't work either

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit current patchlevel

**Additional context**
I was wondering if it might be caused by a unconfigured internetaddress assigned to the ressource

**Comment by rainer-haeberle** [comment]
Update:
you can again remove the room from that meeting . 
But you won't lost this message.
You have to delete the meeting an recreate it from scratch.

**Comment by paulswithers** [comment]
Looking at the mail template code, this is caused by some fields we are setting to make the clickable link appear. I need to investigate a bit further to check functionality, but setting OnlinePlaceToReserce field may solve the problem. This message is appearing if that field is blank and SametimeType is "0". I need to investigate those fields a bit more first, to get more understanding of how they're used.

**Comment by spanky762** [comment]
Hi @rainer-haeberle !  ![image](https://user-images.githubusercontent.com/3831901/129768787-d2be3c05-f1b9-4ce9-9214-15ab335375ef.png)![image](https://user-images.githubusercontent.com/3831901/129768944-9bcf441d-b65a-4cc1-a643-ad1f8c68167f.png)Would you please try making the following changes in your copy of the template code and let us know the results?![image](https://user-images.githubusercontent.com/3831901/129769258-d0e4c6a5-ff60-4fe9-9bf8-36f532e11fa7.png)
Libray domiIntegrator.lss 
Lines 1809, and 2064, set the value for fldList(|SametimeType|) to |3| instead of |0|. 

Library domiSTUtilsBE.lss
Line 95, set the value for fldList("SametimeType") to "3" instead of "0".

![image](https://user-images.githubusercontent.com/3831901/129769258-d0e4c6a5-ff60-4fe9-9bf8-36f532e11fa7.png)


Hope this helps!,
-Devin.

**Comment by ChillUpX** [comment]
Hi @spanky762!

We were facing the same problem like @rainer-haeberle described above. I downloaded the latest release of DOMI and changed your mentioned values (although the line numbers were slightly different) to |3|. After that all tests worked for us, adding/removing a room or resource without any popup message and all invited persons could accept the meeting.

Greetings,
Rony

**Comment by spanky762** [comment]
Fantastic @ChillUpX !   We will get the changes incorporated shortly.

**Comment by rainer-haeberle** [comment]
Thanks to all for working on this 
We are going to add the changes to our DOMI Template and will com back with the results.

I'm afraid it will work as described by ChillUpX :-)

**Comment by rainer-haeberle** [comment]
I've implemented the change to my Mail-File and it works as described.

After that I changed our Domi.nsf and updated our central mail-template with the change.

Many thanks to all involved

From my point of view this bug is solved

**Comment by rainer-haeberle** [comment]
waiting for the next fixed version of domi.nsf

**Comment by spanky762** [comment]
@rainer-haeberle : Thanks for the feedback, we appreciate it!
