### ISSUE TITLE
ZOOM Token expiration 

### ISSUE THREAD

**Issue by vtatarincev** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#113]
when requesting ZOOM token, it works fine, but after some days (approx. week) Token get expired,
May be longer token validity is possible, or when old token is still valid, we can get new token and replace OLD token with new?

right now validity of token is too short.

**Comment by spanky762** [comment]
Hi @vtatarincev, 

Token expiration times are entirely controlled by the various Meeting Service Providers.    When a user creates (or updates) a meeting, DOMI code will pass the user's Authorization token to the appropriate Meeting Service Provider. (REST API call)  If the Provider responds that the Authorization token has expired, DOMI will pass the user's Refresh Token back and request an updated Authorization token.  If the Provider returns a valid set of tokens (both Authorization and Refresh) the DOMI code will automatically update the user's tokens and use the updated Authorization token to proceed with meeting creation / update.  

All of this happens automatically behind the scenes, with no user interaction necessary. 

However, sometimes the Refresh token will also be expired.  In this case DOMI will ask the user to open their credentials document and request a new OAuth2 token from the provider.  This action requires the user to enter their authentication credentials in the browser in order to get a new token.   Unfortunately, due to OAuth2 security requirements for the user to authenticate, there is no way to automate this process.   

Hope this helps explain things!

**Comment by spanky762** [comment]
Closed by mistake.  Re-opening issue for additional discussion.

**Comment by spanky762** [comment]
No additional discussion regarding process automation has occurred.  Background token refresh authorization process has been revised with 12.0.1 Template release.  Closing this issue.
