### ISSUE TITLE
[BUG] Error #1502: JSON parsing

### ISSUE THREAD

**Issue by marcisbe** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#123]
**HCL Product Version**
Notes 12

**Describe the bug**
I try to create new Teams meeting. When I press Schedule Online Meeting > Teams.
Error message is displayed. Error 0. If I press "Validate OAuth Token" in token doc it shows "Token is valid"message and now I can create meeting without error. After about 1 hour error happens again.

log.nsf shows following:
 
Server: 		Local Client
Version: 		Release 12.0; May 14, 2021             ; Build 461
ACL Level: 		Manager
ACL Roles	[admin], [AccessContacts]

2021.10.21 16:34:24 LotusScript Started
2021.10.21 16:34:24 Class: EnhancedLog.CHANGELOGTYPE(): Opened NotesLog [LocalClient]!!C:\IBM\Notes\Data\log.nsf
Domino Online Meeting Integration, 20 JUL 2021, Version: 1.0.3 HF1, Build: 1.12D3
2021.10.21 16:34:24 Library: NotesRESTconsumer.Class: NotesRESTconsumer.PROCESSREQUEST(): 
Response Code: HTTP/1.1 200 Connection established
2021.10.21 16:34:24 Library: NotesRESTconsumer.Class: NotesRESTconsumer.PROCESSREQUEST(): Http POST:  HTTP/1.1 200 Connection established

POST Headers JSON
{
  "Content-Type":"application/json",
   "Authorization":"**********"
}

POST Body JSON
{
  "subject":"Sapulces nosaukums",
  "startDateTime":"2021-10-22T14:00:00+02:00",
  "endDateTime":"2021-10-22T14:50:00+02:00"
}

2021.10.21 16:34:24 Error #1502: JSON parsing for /error worked, but returned "JSON Object" (1) instead of "String" (3).
Library:NotesHttpJsonRequestHelper.Class: NotesAgent_JsonHTTPHelper.FINDSTRINGBYPOINTER();  line #312
Pointer: /error

Stack Logging is Disabled

2021.10.21 16:34:24 Library: domiUtilsFE.DOMINOTIFYRESULT(): 
DOMI Failure
domi.ErrorCode: 0
domi.ErrorMessage: 
domi.ResponseCode: HTTP/1.1 200 Connection established
domi.HTTPstatusCodeType: 2xx Success: The action was successfully received, understood, and accepted

2021.10.21 16:34:26 LotusScript Finished

**Error Message**
![attels](https://user-images.githubusercontent.com/10738166/138289981-f0e0a7ff-c9d6-498c-8c0f-6dc25cc0250e.png)

**Comment by marcisbe** [comment]
Yes it happens, but I found the reason. It was windows environment variable htt_proxy. When I removed it, everything works as expected.

**Comment by tkheuer** [comment]
This is no solution for us. 
Generally the internet traffic is blocked by the firewall in our company environment, if the environment variables http_proxy are not set. 
In this case you would bypass the proxy server and a route the "token refresh traffic" directly in the internet.
I modified the lotusscript code in the domiIntefrator script library a little bit, to workaround this issue. (see attached screenshot).
The token is now refreshed every time, when the users creates a new teams link. In this case the error does not occurs any more.
But it would be nice, if the root cause could be found.
![20-01-_2022_10-36-26](https://user-images.githubusercontent.com/92520525/150314188-c15a3ab0-95f1-488e-9223-d33e5403a741.jpg)
