### ISSUE TITLE
[BUG]Error 1208 : Failed to create an Object

### ISSUE THREAD

**Issue by yvderlet** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#158]
**HCL Product Version**
11.01FP or 12.01

**Describe the bug**
The user create a new meeting and click on Onlime Meeting Webex....

**Error Message**
Error : 1208 : Failed to create an Object

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**
[log.zip](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/files/9065013/log.zip)

**Comment by spanky762** [comment]
Also, as you are using 12.0.1FP1, can you please open an official support ticket so the production team is "officially" aware of this issue? 

 @INeedCaffeine I will let you know as soon as I figure something out, but would like to chat with you about this.

**Comment by spanky762** [comment]
Hello @yvderlet!

I have reviewed (stepped through testing) the current 12.0.1 FP 1 code.  

When an SSL connection failure occurs the failure information is written to the log and the exception is cleared (via a Resume ExitPoint call).  The calling code does not receive back a valid target NotesJSONNavigator (because in this case the SSL connection failure carries no valid JSON), and throws the "Failed to Create an Object" exception.   

The code seems to be working correctly and as designed.

Please take a look at these KB articles to help you resolve the SSL / Proxy issue.   

- https://support.hcltechsw.com/csm/en?id=kb_article&sysparm_article=KB0073832 
- https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0096255 

If you are still having problems after following the the KB articles, please open a support ticket, as this is a 12.0.1 (Production) issue.  

Hope this helps!

**Comment by yvderlet** [comment]
Hello,

We are using Notes 12.01 FP1 with Mail 11 template.

I already opened a case to HCL and as it is a Mail 11, they do not investigate....

In this case, I have only 1 user that has this problem... I will investigate further to find the proxy settings...

But I have the same issue when I create a calendar entry based from a mail (I take a mail --> Copy into New Calendar...

And get the same error 1208.

In template v12, HCL solve the problem with the following ini parameter : DOMI_Do_not_send_agenda=1

I will prepare a Mail 12 template for preparing the migration, but I create this bug as you may have someone that has the same issue.

Thank you
